homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon
  temperature_unit: C
  unit_system: imperial

  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
counter:
dhcp:
frontend:
history:
image:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
# media_source:
# mobile_app:
ssdp:
sun:
system_health:
timer:
usb:
zeroconf:

discovery:

device_tracker:
  # TODO: figure this out
  # - platform: huawei_router
  #   host: 192.168.1.1
  #   username: !secret router_user
  #   password: !secret router_pass
  #   new_device_defaults:
  #     track_new_devices: true

  - platform: ping
    hosts:
      dialbox: 192.168.1.64
      extender: 192.168.1.65
      pixelpad: 192.168.1.66
      pi0: 192.168.1.67

person:
  - name: Kevin
    id: kevin
    user_id: 0c2a75f55ae64a3aa527cd7855bee058
    device_trackers:
      - device_tracker.dialbox
      - device_tracker.pixelpad

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
