homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation

  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Lisbon
  temperature_unit: C
  unit_system: imperial

  customize: !include customize.yaml
  packages: !include_dir_named packages

default_config:

device_tracker:
  # TODO: figure this out
  # - platform: huawei_router
  #   host: 192.168.1.1
  #   username: !secret router_user
  #   password: !secret router_pass
  #   new_device_defaults:
  #     track_new_devices: true

  - platform: ping
    hosts:
      applebox: 192.168.1.64
      dialbox: 192.168.1.73
      extender: 192.168.1.65
      pi1: 192.168.1.71

person:
  - name: Kevin
    id: kevin
    user_id: 42369f615a514199aac15c4f8bcece33
    device_trackers:
      - device_tracker.dialbox
      - device_tracker.galaxypad

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
