version: 2.1

orbs:
  linter: thekevjames/linter@0

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
          pre-steps:
            - run: apt-get update
            - run: apt-get install -qy shellcheck
