version: 2.1

orbs:
  linter: talkiq/linter@3

executors:
  python:
    docker:
      - image: python:3.7.16
    resource_class: small

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          executor: python
