version: '3.8'

services:
  hass:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hass:/config:Z

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homepage:/app/config:Z
