version: '3.8'

services:
  hass:
    container_name: hass
    image: docker.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Lisbon
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/src/experiments/selfhost/hass:/config:Z
