version: '3.8'

services:
  calibre:
    profiles:
      - applebox
    container_name: calibre
    image: lscr.io/linuxserver/calibre:latest
    ports:
      - 8080:8080
      - 8081:8081
      - 8181:8181
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/sync/books:/data/books
      - ./calibre:/config:Z

  calibre-web:
    profiles:
      - applebox
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    ports:
      - 8083:8083
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:calibre-web-dtrpg-metadata
    volumes:
      - /mnt/4tb/sync/books:/data/books
      - ./calibre-web:/config:Z

  hass:
    profiles:
      - applebox
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hass:/config:Z

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /mnt/1tb:/mnt/1tb
      - /mnt/4tb:/mnt/4tb
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homepage:/app/config:Z

  jellyfin:
    profiles:
      - applebox
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:release
    ports:
      - 8096:8096
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/movies:/data/media/movies
      - /mnt/4tb/shows:/data/media/shows
      - ./jellyfin:/config:Z

  prowlarr:
    profiles:
      - pi-1
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - ./prowlarr:/config:Z

  qbittorrent:
    profiles:
      - pi-1
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - ./qbittorrent:/config:Z

  radarr:
    profiles:
      - pi-1
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/movies:/data/media/movies
      - ./radarr:/config:Z

  readarr:
    profiles:
      - applebox
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    ports:
      - 8787:8787
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/sync/books:/data/books
      - ./readarr:/config:Z

  sonarr:
    profiles:
      - pi-1
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/shows:/data/media/shows
      - ./sonarr:/config:Z

  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/sync:/data/sync
      - ./syncthing:/config:Z
