version: '3.8'

services:
  hass:
    container_name: hass
    image: docker.io/homeassistant/home-assistant:stable
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hass:/config:Z
