version: '3.8'  # TODO: bump

secrets:
  jira_auth_token:
    file: ./mosura/jira_auth_token
  jira_auth_user:
    file: ./mosura/jira_auth_user
  jira_domain:
    file: ./mosura/jira_domain
  jira_label_okr:
    file: ./mosura/jira_label_okr
  jira_project:
    file: ./mosura/jira_project

services:
  caddy:
    # TODO: better way of specififying profiles, syncing with IPs, etc
    profiles:
      - applebox
    image: quay.io/thekevjames/caddy-security:2.6.4-1.1.19
    command: caddy run --config /config/caddy/Caddyfile --adapter caddyfile
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ./secrets/google.env
    volumes:
      - ./caddy:/config/caddy:Z

  # TODO: configure ssh tunneling
  cloudflared:
    profiles:
      - applebox
    image: docker.io/cloudflare/cloudflared:latest
    command: tunnel run
    container_name: cloudflared
    restart: unless-stopped
    volumes:
      - ./cloudflared:/home/nonroot/.cloudflared:Z

  hass:
    profiles:
      - applebox
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hass:/config:Z

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /mnt/1tb:/mnt/1tb
      - /mnt/4tb:/mnt/4tb
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homepage:/app/config:Z

  jellyfin:
    profiles:
      - applebox
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/movies:/data/media/movies
      - /mnt/4tb/shows:/data/media/shows
      - ./jellyfin:/config:Z

  mosura:
    profiles:
      - applebox
    image: quay.io/thekevjames/mosura:latest
    container_name: mosura
    restart: unless-stopped
    environment:
      - MOSURA_HEADER_USER_EMAIL=X-Token-User-Email
      - MOSURA_PORT=8080
      - MOSURA_APPDATA=/data
    secrets:
      - jira_auth_token
      - jira_auth_user
      - jira_domain
      - jira_label_okr
      - jira_project
    volumes:
      - ./mosura:/data:Z

  prowlarr:
    profiles:
      - pi-1
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - ./prowlarr:/config:Z

  qbittorrent:
    profiles:
      - pi-1
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - ./qbittorrent:/config:Z

  radarr:
    profiles:
      - pi-1
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/movies:/data/media/movies
      - ./radarr:/config:Z

  sonarr:
    profiles:
      - pi-1
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/data/torrents
      - /mnt/4tb/shows:/data/media/shows
      - ./sonarr:/config:Z

  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/4tb/sync:/data/sync
      - ./syncthing:/config:Z
