version: '3.8'

services:
  hass:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Lisbon
    # network_mode: host
    # privileged: true
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - ./hass:/config
