version: '3.8'

services:
  hass:
    container_name: hass
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - 8123:8123
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./hass:/config:Z

  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homepage:/app/config:Z

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:release
    ports:
      - "8096:8096"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/mnt/done
      - /mnt/4tb/torrent/keep:/mnt/keep
      - /mnt/4tb/torrent/seeding:/mnt/seeding
      - ./jellyfin:/config

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release
    ports:
      - 8080:8080
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /mnt/1tb/torrents:/mnt/done
      - /mnt/4tb/torrent/keep:/mnt/keep
      - /mnt/4tb/torrent/pending:/mnt/pending
      - /mnt/4tb/torrent/seeding:/mnt/seeding
      - /mnt/4tb/torrent/watch:/mnt/watch
      - ./qbittorrent:/config
