---
- Media:
    - Jellyfin:
        href: http://192.168.1.64:8096/
        description: Media Server
        icon: jellyfin
        server: docker-local
        container: jellyfin

- Torrents:
    - qBittorrent:
        href: http://192.168.1.71:8080/
        description: Torrent Client
        icon: qbittorrent
        server: docker-local
        container: qbittorrent

- Infrastructure:
    - HASS:
        href: http://192.168.1.64:8123/
        description: Home Assistant
        icon: home-assistant
        server: docker-local
        container: hass
    - Homepage:
        href: http://192.168.1.64:3000/
        description: Homepage on applebox
        icon: mdi-home-circle
        server: docker-local
        container: homepage
    - Homepage:
        href: http://192.168.1.71:3000/
        description: Homepage on pi-1
        icon: mdi-home-circle
        server: docker-local
        container: homepage

- Networking:
    - Pi-Hole:
        href: http://192.168.1.71/admin/
        description: Pi-Hole Admin Portal
        icon: pi-hole
        widget:
            type: pihole
            url: http://192.168.1.71
    - Router:
        href: http://192.168.1.1/
        description: Router Admin Portal
        icon: router
