---
- Infrastructure:
    - HASS:
        href: http://192.168.1.71:8123/
        description: Home Assistant
        icon: home-assistant
        server: my-docker
        container: hass

- Networking:
    - Pi-Hole:
        href: http://192.168.1.71/admin/
        description: Pi-Hole Admin Portal
        icon: pihole
        widget:
            type: pihole
            url: http://192.168.1.71
    - Router:
        href: http://192.168.1.1/
        description: Router Admin Portal
        icon: router
