---
- Media:
    - Jellyfin:
        href: http://192.168.1.71:8096/
        description: Media Server
        icon: jellyfin
        server: docker-local
        container: jellyfin

- Torrents:
    - qBittorrent:
        href: http://192.168.1.71:8080/
        description: Torrent Client
        icon: qbittorrent
        server: docker-local
        container: qbittorrent

- Infrastructure:
    - HASS:
        href: http://192.168.1.71:8123/
        description: Home Assistant
        icon: home-assistant
        server: docker-local
        container: hass

- Networking:
    - Pi-Hole:
        href: http://192.168.1.71/admin/
        description: Pi-Hole Admin Portal
        icon: pihole
        widget:
            type: pihole
            url: http://192.168.1.71
    - Router:
        href: http://192.168.1.1/
        description: Router Admin Portal
        icon: router
