# TODO: service widgets (require auth, plaintext in this file :()
---
- Control:
    - HASS:
        href: http://192.168.1.64:8123/
        description: Home Assistant
        icon: home-assistant
        server: docker-local
        container: hass
    - Homepage:
        href: http://192.168.1.64:3000/
        description: Homepage on applebox
        icon: mdi-home-circle
        server: docker-local
        container: homepage
    - Homepage:
        href: http://192.168.1.71:3000/
        description: Homepage on pi-1
        icon: mdi-home-circle
        server: docker-local
        container: homepage

- Media:
    - Jellyfin:
        href: http://192.168.1.64:8096/
        description: Media Server
        icon: jellyfin
        server: docker-local
        container: jellyfin
    - Radarr:
        href: http://192.168.1.71:7878/
        description: Movie Collection Manager
        icon: radarr
        server: docker-local
        container: radarr
    - Sonarr:
        href: http://192.168.1.71:8989/
        description: TV Show Collection Manager
        icon: sonarr
        server: docker-local
        container: sonarr

- Torrents:
    - qBittorrent:
        href: http://192.168.1.71:8080/
        description: Torrent Client
        icon: qbittorrent
        server: docker-local
        container: qbittorrent
    - Prowlarr:
        href: http://192.168.1.71:9696/
        description: Indexer Manager
        icon: prowlarr
        server: docker-local
        container: prowlarr

- Books:
    - Calibre-Web:
        href: http://192.168.1.64:8083/
        description: E-Book Manager Frontend
        icon: calibre-web
        server: docker-local
        container: calibre-web
    - Calibre:
        href: http://192.168.1.64:8080/
        description: E-Book Manager
        icon: calibre
        server: docker-local
        container: calibre
    - Radarr:
        href: http://192.168.1.64:8787/
        description: E-Book Collection Manager
        icon: readarr
        server: docker-local
        container: readarr

- Networking:
    - Pi-Hole:
        href: http://192.168.1.71:8000/admin/
        description: Pi-Hole Admin Portal
        icon: pi-hole
    - Router:
        href: http://192.168.1.1/
        description: Router Admin Portal
        icon: router
    - Cloudflared:
        description: DNS Tunnel
        icon: cloudflare-zero-trust
        server: docker-local
        container: cloudflared

- Services:
    - Mosura:
        href: https://mosura.thekev.in/
        description: Task Management Frontend
        server: docker-local
        container: mosura
    - Caddy:
        href: https://auth.thekev.in/
        description: Secure Reverse Proxy
        icon: caddy
        server: docker-local
        container: syncthing
    - Syncthing:
        href: http://192.168.1.64:8384/
        description: Syncthing on applebox
        icon: syncthing
        server: docker-local
        container: syncthing
    - Syncthing:
        href: http://192.168.1.71:8384/
        description: Syncthing on pi-1
        icon: syncthing
        server: docker-local
        container: syncthing
