---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
  labels:
    run: app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      name: app
      namespace: default
      labels:
        run: app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: thekevjames/o11y-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 110Mi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    run: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      run: prometheus
  template:
    metadata:
      labels:
        run: prometheus
    spec:
      containers:
        - name: prometheus
          image: thekevjames/o11y-prometheus:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 100m
              memory: 510Mi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus/
      volumes:
        - name: prometheus-storage
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    run: alertmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      run: alertmanager
  template:
    metadata:
      labels:
        run: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: thekevjames/o11y-alertmanager:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9093
          resources:
            limits:
              cpu: 100m
              memory: 110Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
kind: Service
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    run: alertmanager
  ports:
  - protocol: TCP
    port: 9093
    targetPort: 9093
