pageInfo:
  title: HomeLab
  navLinks:
    - title: Home
      path: /
    - title: Source Code
      path: https://github.com/TheKevJames/experiments/tree/master/selfhost

appConfig:
  theme: dracula
  statusCheck: true
  enableServiceWorker: true

sections:
  - name: Networking
    items:
        - title: Router
          description: Router
          icon: hl-router
          url: http://192.168.1.1/
        - title: Pi-Hole
          description: PiHole
          icon: hl-pihole
          url: http://192.168.1.71/admin

  - name: Networking
    items:
        - title: HASS
          description: Home Assistant
          icon: hl-router
          url: http://192.168.1.71:8123/
