{
 "title": "App",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Job Concurrency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (kubernetes_pod_name) (system_in_flight_total)"
    }
   ]
  },
  {
   "title": "Job Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (stage, le) (rate(job_latency_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(job_failures_total[5m])) / sum(rate(job_latency_seconds_count[5m]))"
    }
   ]
  }
 ]
}